config/routes.rb
Rails.application.routes.draw do
  resources :products

  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Aggregator::Queries::Product.new.all_with_reviews
  end

  def show
    @product = Aggregator::Queries::Product.new.find(params[:id])
  end

  def create
    product_id = WalmartProductUrlParser.extract_product_identifier(params[:product_url])
    command    = Aggregator::Commands::FetchProductInformation.new(product_id: product_id)

    Aggregator::Handlers::FetchProduct.new(command).call
    redirect_to products_path, notice: "Successfully added new product."
  rescue ArgumentError, Aggregator::Errors::ProductAlreadyExistError => e
    flash.alert = e.message
    render :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WalmartAggregator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "Add product", new_product_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Reviews Count</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.reviews.size %></td>
        <td>
          <%= link_to "Details", product_path(product) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Add new product</h1>
<% if flash.alert.present? %>
  <h3 style="color: red"><%= flash.alert %></h3>
<% end %>

<%= form_tag products_path, method: :post do %>
  <%= label_tag "Product url" %>
  <%= text_field_tag :product_url %>
  <%= submit_tag "Add" %>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p><%= number_to_currency(@product.price) %></p>
<p>Reviews</p>
<ul>
  <% @product.reviews.each do |review| %>
    <li>
      <dl>
        <dt>Title</dt>
        <dd><%= review.title %></dd>
        <dt>Reviewer</dt>
        <dd><%= review.reviewer %></dd>
        <dt>Content</dt>
        <dd><%= review.content %></dd>
      </dl>
    </li>
  <% end %>
</ul>